"""Updated LostItem model

Revision ID: 3f70ffc805ba
Revises: 
Create Date: 2025-04-20 02:51:47.772042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f70ffc805ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_found', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('finder_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('lost_item_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['finder_id'], ['id'])
        batch_op.drop_column('title')
        batch_op.drop_column('user_id')
        batch_op.drop_column('date_lost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_lost', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('lost_item_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('finder_id')
        batch_op.drop_column('image_url')
        batch_op.drop_column('date_found')

    # ### end Alembic commands ###
